### ISSUE TITLE
Feature request: Ability to use sigmatch without compile time literals using runtime variables instead

### ISSUE THREAD

**Issue by MattMills** [SpriteOvO/sigmatch#4]
Hello again @SpriteOvO,

Your code uses much newer C++ concepts than my brain does, and I'm at a complete loss while trying to build a Lua module that allows use of sigmatch searches from within Lua as I can't figure out how to use ""_sig with a variable std::string received from Lua...

Is this possible or would it require changes to the way the library works?

Thanks,
Matt.

**Comment by SpriteOvO** [comment]
`""_sig` only accepts string from compile-time, it needs changes to support runtime signature parsing.

**Comment by MattMills** [comment]
OK, I've changed the title to represent a feature request instead, assuming you are OK with that... if not I can try to fork and see if I can manipulate the existing code to implement it myself, but to be honest your C++ is much more advanced than my understanding, I haven't learned many of these newer features.

**Comment by SpriteOvO** [comment]
Some hints:

1. Changing the `consteval` to `constexpr` for all function involved in `_sig` function, this makes them can be called at both runtime and compile-time.

2. During the first step, you need to figure out how to reimplement the macro `SIGMATCH_CONSTEVAL_STATIC_ASSERT` in order to report an error to caller for runtime parsing. (Probably have to use `if constexpr` and [`std::is_constant_evaluated`](https://en.cppreference.com/w/cpp/types/is_constant_evaluated))

3. Make a static member function for `signature` for runtime parsing, e.g.
    ```cpp
    signature signature::parse(std::string_view) noexcept
    ```

Feel free to try it out, just make it work for yourself and then you can learn a lot from it ;)

I will try to officially implement it in this repo after I finish my other work.

**Comment by MattMills** [comment]
@SpriteOvO if I can bother you for another hint, I've spent some more time on this and where I'm stuck right now is what the heck to do with consteval_str_buffer... since it takes size as a template arg and that needs to be a compile time constant; am I looking at this in the wrong way, or do I just need to add a second struct with a dynamically sized array?

**Comment by SpriteOvO** [comment]
> do I just need to add a second struct with a dynamically sized array?

@MattMills No, `constexpr` can handle `std::string_view` well, so `consteval_str_buffer` is only needed for the entry `consteval` function `parse_sig_str`. For deeper functions, the [NTTP](https://en.cppreference.com/w/cpp/language/template_parameters) `consteval_str_buffer` can be simply replaced with a normal parameter `std::string_view`.

Don't worry, I have started trying implement it in this repo officially.
